/**
 * prove_chain.ts — Hour-1 de-risk script
 *
 * Run BEFORE building the app. Proves the Aiken contract works on preprod.
 * Locks 5 tADA, then immediately releases with CompleteTask redeemer.
 * Prints both tx hashes → open on preprod.cardanoscan.io
 *
 * Usage:
 *   npx ts-node scripts/prove_chain.ts
 *
 * Requires:
 *   BLOCKFROST_PROJECT_ID_PREPROD, OPERATOR_SKEY_HEX, OPERATOR_VKH in .env
 *   plutus.json generated by: cd contracts/task_escrow && aiken build
 */

import * as dotenv from "dotenv";
dotenv.config();

import {
  Lucid,
  Blockfrost,
  Data,
  applyParamsToScript,
  validatorToAddress,
  type SpendingValidator,
} from "@lucid-evolution/lucid";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const EXPLORER = "https://preprod.cardanoscan.io/transaction";

async function main() {
  const projectId = process.env.BLOCKFROST_PROJECT_ID_PREPROD;
  const skey = process.env.OPERATOR_SKEY_HEX;
  const operatorVkh = process.env.OPERATOR_VKH;

  if (!projectId || !skey || !operatorVkh) {
    console.error("Missing BLOCKFROST_PROJECT_ID_PREPROD, OPERATOR_SKEY_HEX, or OPERATOR_VKH in .env");
    process.exit(1);
  }

  const lucid = await Lucid(
    new Blockfrost("https://cardano-preprod.blockfrost.io/api/v0", projectId),
    "Preprod"
  );
  lucid.selectWallet.fromPrivateKey(skey);

  const blueprintPath = path.join(__dirname, "../contracts/task_escrow/plutus.json");
  if (!fs.existsSync(blueprintPath)) {
    console.error("plutus.json not found. Run: cd contracts/task_escrow && aiken build");
    process.exit(1);
  }
  const blueprint = JSON.parse(fs.readFileSync(blueprintPath, "utf-8"));
  const compiled = blueprint.validators.find(
    (v: any) => v.title === "escrow.task_escrow.spend"
  );
  if (!compiled) { console.error("Validator not found in blueprint"); process.exit(1); }

  const validator: SpendingValidator = {
    type: "PlutusV3",
    script: applyParamsToScript(compiled.compiledCode, [operatorVkh]),
  };
  const scriptAddress = validatorToAddress("Preprod", validator);
  console.log("Script address:", scriptAddress);

  const DatumSchema = Data.Object({
    task_id: Data.Bytes(),
    poster: Data.Bytes(),
    agent: Data.Bytes(),
    amount: Data.Integer(),
  });

  const walletAddr = await lucid.wallet().address();
  const walletUtxos = await lucid.utxosAt(walletAddr);
  console.log("Operator wallet:", walletAddr);
  console.log("UTXOs:", walletUtxos.length);

  // --- LOCK ---
  const taskId = Buffer.from("prove-chain-001").toString("hex");
  const posterPkh = operatorVkh; // operator acts as poster for this test
  const agentPkh = operatorVkh;  // operator acts as agent for this test
  const lovelace = BigInt(5_000_000);

  const datum = Data.to(
    { task_id: taskId, poster: posterPkh, agent: agentPkh, amount: lovelace },
    DatumSchema as any
  );

  console.log("\nLocking 5 tADA...");
  const lockTx = await lucid.newTx()
    .pay.ToContract(scriptAddress, { kind: "inline", value: datum }, { lovelace })
    .complete();
  const lockSigned = await lockTx.sign.withWallet().complete();
  const lockHash = await lockSigned.submit();
  console.log("LOCK TX:", lockHash);
  console.log("Explorer:", EXPLORER + "/" + lockHash);

  // wait for confirmation
  console.log("\nWaiting 60s for confirmation...");
  await new Promise((r) => setTimeout(r, 60_000));

  // --- RELEASE ---
  const scriptUtxos = await lucid.utxosAt(scriptAddress);
  console.log("Script UTXOs found:", scriptUtxos.length);
  
  // Find our UTXO by txHash from the lock transaction
  const utxo = scriptUtxos.find((u) => u.txHash === lockHash) || scriptUtxos[0];
  if (!utxo) { console.error("UTXO not found at script address"); process.exit(1); }
  console.log("Found UTXO:", utxo.txHash, "index:", utxo.outputIndex);

  const RedeemSchema = Data.Enum([Data.Literal("CompleteTask"), Data.Literal("RefundPoster")]);
  const redeemer = Data.to("CompleteTask", RedeemSchema as any);

  console.log("\nReleasing with CompleteTask...");
  const releaseTx = await lucid.newTx()
    .collectFrom([utxo], redeemer)
    .attach.SpendingValidator(validator)
    .pay.ToAddress(walletAddr, { lovelace })
    .addSigner(walletAddr)
    .complete({ localUPLCEval: false });
  const releaseSigned = await releaseTx.sign.withWallet().complete();
  const releaseHash = await releaseSigned.submit();
  console.log("RELEASE TX:", releaseHash);
  console.log("Explorer:", EXPLORER + "/" + releaseHash);

  console.log("\n=== CHAIN PROOF COMPLETE ===");
  console.log("Lock:   ", EXPLORER + "/" + lockHash);
  console.log("Release:", EXPLORER + "/" + releaseHash);
  console.log("General Track criterion: BANKED ✓");
}

main().catch((e) => { console.error(e); process.exit(1); });
